# Generated by Django 3.2.18 on 2023-05-02 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribeuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='event',
            name='formatEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.formatevent', verbose_name='Формат мероприятии'),
        ),
        migrations.AddField(
            model_name='event',
            name='themeOfEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.themeofevent', verbose_name='Тема мероприятии'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
